kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "dawarich.fullname" . }}-config
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}


